---
- name: This play installs needed tools to provision infrastructure VMs
  hosts: vm_host
  vars_files:
    - vars/libvirt.yml
  tasks:

    - name: Download and provision Terraform
      unarchive: 
        src: ../resources/terraform_0.12.24_linux_amd64.zip
        dest: /usr/bin/
        mode: 755
        remote_src: yes
      become: true

    - name: Install qemu, libvirt, git
      yum:
        name: "{{ virtualization_packages }}"
        state: latest
      become: true

    - name: Virtualization services are enabled
      service:
        name: libvirtd
        state: started
        enabled: true
      become: true

    - name: Ensures terraform libvirt-provider directory exists
      file:
        path: ~/libvirt-provider
        state: directory
        mode: 0744

    - name: Download terraform libvirt provider project to the libvirt-provider directory
      unarchive:
        src: ../resources/terraform-provider-libvirt-master.zip
        dest: ~/libvirt-provider
        mode: 755
        remote_src: yes
      become: true

    - name: Run 'install' target on libivrt-provider
      make:
        chdir: ~/libvirt-provider/terraform-provider-libvirt-master
        target: install

    - name: Ensures terraform plugins directory exists
      file:
        path: ~/.terraform.d/plugins
        state: directory
        mode: 0744

    - name: Copy libvirt provider to plugins directory
      copy:
        src: "{{ gopath }}/bin/terraform-provider-libvirt"
        dest: ~/.terraform.d/plugins/
        remote_src: true
        mode: 0755

    - name: Ensure pool path exists
      file:
        path: "{{ libvirt.storage.pool_path }}"
        state: directory
      become: true

    - name: Define libvirt network
      virt_net:
        command: define
        name: "{{ libvirt.network.network_name }}"
        xml: '{{ lookup("template", "templates/libvirt_network.xml.j2") }}'

    - name: Make libvirt network autostart
      virt_net:
        name: "{{ libvirt.network.network_name }}"
        autostart: true

    - name: Start libvirt network
      virt_net:
        command: start
        name: "{{ libvirt.network.network_name }}"
        state: active

    - name: Define libvirt pool
      virt_pool:
        command: define
        name: "{{ libvirt.storage.pool_name }}"
        xml: '{{ lookup("template", "templates/libvirt_pool.xml.j2") }}'

    - name: Make libvirt pool autostart
      virt_pool:
        name: "{{ libvirt.storage.pool_name }}"
        autostart: true

    - name: Start libvirt pool
      virt_pool:
        command: start
        name: "{{ libvirt.storage.pool_name }}"
        state: active
