---
- name: Creating a workspace on Bastion
  hosts: bastion 
  gather_facts: no
  tasks:

    - name: Erasing dnsmasq lease
      file:
        path: /var/lib/dnsmasq/dnsmasq.leases
        state: absent
      become: true

    - name: Creating workspace
      file:
        state: directory
        path: "{{ item }}"
      loop: 
        - "{{ workspace_directory.base_path }}/{{ workspace_directory.config_dir }}"
        - "~/.ssh"

    - name: Creating ssh keys if not exists
      openssh_keypair:
        path: "~/.ssh/id_rsa"

    - name: Creating tftpboot and nginx workspace
      file:
        state: directory
        path: "{{ item }}"
      loop: 
        - "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}"
        - "{{ nginx_document_root }}/{{ nginx_workspace_dir }}"
      become: True

    - name: Downloading installer and OCP cli
      unarchive:
        src: "{{ item }}"
        dest: /usr/local/bin
        remote_src: no
      become: True
      loop:
        - "{{ downloads.ocp.base_url + downloads.ocp.ocp_oc_cli }}"
        - "{{ downloads.ocp.base_url + downloads.ocp.ocp_installer }}"
      when: not (skip_download | bool)
      
    - name: Checking for openshift-install tool
      command: openshift-install
      register: output
      failed_when: output.rc !=0

    - name: Checking for OCP cli tool
      command: oc
      register: output
      failed_when: output.rc !=0

    - block:
        - name: Download initramfs and kernel
          copy:
            src: "{{ downloads.rhcos.base_url + item }}"
            dest: "{{ tftp_boot_root }}/{{ tftp_workspace_dir }}/{{ item }}"
            remote_src: no
            mode: 0755
          loop:
            - "{{ downloads.rhcos.initramfs }}"
            - "{{ downloads.rhcos.kernel }}"

        - name: Download Red Hat CoreOS for bare metal
          copy:
            src: "{{ downloads.rhcos.base_url + downloads.rhcos.coreos }}"
            dest: "{{ nginx_document_root }}/{{ nginx_workspace_dir }}/{{ downloads.rhcos.coreos }}"
            remote_src: no
            mode: 0755

      when: not (skip_download | bool)
      become: true
